x-default-logging: &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "1"
services:
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "5011:6379"
        volumes:
            - /home/redis/redis_data:/data
        restart: always
        command: redis-server --requirepass fweqfqe24fwe6rew
        networks:
            - qipf-network
        logging: *default-logging
networks:
    qipf-network:
        external: true
