# Configuration for telegraf agent
# |> map(fn: (r) => ({_time: r._time, _measurement: r._measurement, _field: "gb_free", _value: r._value / 1073741824, device: r.device, host: r.host}))
[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000

  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"

  precision = ""
  
  #logfile = "/home/log/telegraf.log"

  hostname = "VMMIS-LAPTOP"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["http://192.168.88.131:11205"]

  token = "qiginfluxdbtoken"

  organization = "qigorg"

  bucket = "metrics"

[[inputs.docker]]
	## Docker Endpoint
	##   To use TCP, set endpoint = "tcp://[ip]:[port]"
	##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
	endpoint = "unix:///var/run/docker.sock"

	gather_services = false

	container_names = []

	source_tag = false

	container_name_include = []
	container_name_exclude = []

	storage_objects = []

	## Timeout for docker list, info, and stats commands
	timeout = "5s"

	docker_label_include = []
	docker_label_exclude = []

	## Which environment variables should we use as a tag
	tag_env = ["JAVA_HOME", "HEAP_SIZE"]